# .github/workflows/app.yaml
name: CICD
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y
          pip install -r requirements.txt
      - name: Set Env variables
        run: "echo TEST_SCOPE=CICD-OPENSOURCE >> $GITHUB_ENV"
      - name: Run Test suite
        run: |
          pytest -vvv -s -n auto --maxprocesses=8 --dist loadgroup
      - name: generate list of providers and features markdown
        run: "python -m edenai_apis.utils.documentation"
      - name: generate doc
        run: |
          cd .docsrc
          rm -rf _build/**
          rm -rf _autosummary/*
          sphinx-apidoc -o _build/ ../edenai_apis/
          make html
          cp -r _build/html/* ../docs/

  generate_doc_and_deploy:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
