# .github/workflows/app.yaml
name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg -y
          pip install -r requirements.txt
      - name: Set Env variables
        run: "echo 'export TEST_SCOPE=CICD-OPENSOURCE' >> $GITHUB_ENV"
      - name: Run Test suite
        run: |
          pytest -vvv -s -n auto --maxprocesses=8
